# site settings
title: Miles Gratz
subtitle:
email: milesgratz@gmail.com
description: 'System Engineer // PowerShell Developer<br />Coffee & Bicycle Enthusiast'
baseurl: # the subpath of your site, e.g. /blog
url: "https://milesgratz.github.io" # the base hostname & protocol for your site
author: Miles Gratz
street_address:
city: Chicago
state: IL
zip_code:
country: USA
phone: (708) 446-4185

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/milesgratz
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/milesgratz
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed